[package]
name = "serde_sjson"
version = "0.1.0"
edition = "2021"
keywords = ["serde", "serialization", "sjson"]
description = "An SJSON serialization file format"
categories = ["encoding", "parser-implementations"]

[dependencies]
serde = { version = "1.0.147", default-features = false }

[dev-dependencies]
serde = { version = "1.0.147", features = ["derive"] }
